---
- hosts: all
  gather_facts: yes
  sudo: yes

  vars_files:
    - vars/main.yml

  roles:
    - ansiblebit.oracle-java
    - zzet.postgresql
    - hectcastro.tomcat

  tasks:
    - name: Set Tomcat JAVA_HOME
      lineinfile: dest=/etc/default/tomcat7 regexp=JAVA_HOME= line=JAVA_HOME={{oracle_java_home}}
