---
- hosts: all
  gather_facts: yes
  sudo: yes

  vars_files:
    - vars/main.yml

  roles:
    - ansiblebit.oracle-java
    - zzet.postgresql
    - nodesource.node
    - geerlingguy.git

  tasks:
    - name: updating submodules
      command: git submodule update --init --recursive
      args:
        chdir: /vagrant

    - name: setting api submodule head to master
      command: "{{ item }}"
      with_items:
        - git checkout master
        - git pull origin master
      args:
        chdir: /vagrant/api

    - name: setting ui submodule head to master
      command: "{{ item }}"
      with_items:
        - git checkout master
        - git pull origin master
      args:
        chdir: /vagrant/ui

    - name: installing bower
      npm: name=bower global=yes

    - name: installing grunt
      npm: name=grunt global=yes
      npm: name=grunt-cli global=yes

    - name: installing ui packages
      command: npm install
      args:
        chdir: /vagrant/ui
